config/routes.rb
Rails.application.routes.draw do
  root 'archives#home'
  get '/login', to: 'login#login_form'
  post '/login', to: 'login#login'
  get '/logout', to: 'login#logout'
  # resources :sent_bibliographies
  resources :archives do
    collection do
      get 'labels'
      post 'labels', to: 'archives#generate_labels'
    end
  end
  # resources :subcategories
  # resources :bibliography_styles
  # resources :fields
  resources :authors
  # resources :destinations
  resources :languages
  # resources :countries
  # resources :categories
  # resources :document_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :archives
  has_and_belongs_to_many :countries
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]
  skip_before_action :require_login, only: [:index, :show]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all.order(:name)
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
  end

  # GET /languages/new
  def new
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:lang_off, :name, :french_name, :ethno, :alcam, :alcno, :alcnotes, :ethnotes, :part_of_country)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_with(model: language, local: true) do |form| %>
  <% if language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% language.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lang_off %>
    <%= form.text_field :lang_off, id: :language_lang_off %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :language_name %>
  </div>

  <div class="field">
    <%= form.label :french_name %>
    <%= form.text_field :french_name, id: :language_french_name %>
  </div>

  <div class="field">
    <%= form.label :ethno %>
    <%= form.text_field :ethno, id: :language_ethno %>
  </div>

  <div class="field">
    <%= form.label :alcam %>
    <%= form.text_field :alcam, id: :language_alcam %>
  </div>

  <div class="field">
    <%= form.label :alcno %>
    <%= form.text_field :alcno, id: :language_alcno %>
  </div>

  <div class="field">
    <%= form.label :alcnotes %>
    <%= form.text_area :alcnotes, id: :language_alcnotes %>
  </div>

  <div class="field">
    <%= form.label :ethnotes %>
    <%= form.text_area :ethnotes, id: :language_ethnotes %>
  </div>

  <div class="field">
    <%= form.label :part_of_country %>
    <%= form.select :part_of_country, options_for_select([['',''],['Anglophone', 'anglophone'],['Francophone', 'francophone']]), id: :language_part_of_country %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Languages</h1>

<% if logged_in? %>
    <p><%= button_to 'Add Language', new_language_path, method: :get, class: 'btn btn-primary' %></p>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>French name</th>
      <th>Ethno</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @languages.each do |language| %>
      <tr>
        <td><%= link_to language.name, language %></td>
        <td><%= language.french_name %></td>
        <td><%= language.ethno %></td>
        <td><%= link_to 'View Archives', archives_path(language: language) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New Language</h1>

<%= render 'form', language: @language %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<h2><%= @language.name %></h2>

<% if logged_in? %>
    <p>
      <%= link_to 'Edit', edit_language_path(@language) %>
    </p>
<% end %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Lang off:</strong>
  <%= @language.lang_off %>
</p>

<p>
  <strong>French name:</strong>
  <%= @language.french_name %>
</p>

<p>
  <strong>Ethno:</strong>
  <%= @language.ethno %>
</p>

<p>
  <strong>Alcam:</strong>
  <%= @language.alcam %>
</p>

<p>
  <strong>Alcno:</strong>
  <%= @language.alcno %>
</p>

<p>
  <strong>Alcnotes:</strong>
  <%= @language.alcnotes %>
</p>

<p>
  <strong>Ethnotes:</strong>
  <%= @language.ethnotes %>
</p>

<p>
  <strong>Part of country:</strong>
  <%= @language.part_of_country %>
</p>

<h3>Related Archives</h3>
<table class="table">
  <tr>
    <th>Archive Number</th>
    <th>Title</th>
    <th>Authors</th>
  </tr>
  <% @language.archives.each do |archive| %>
    <tr>
      <td><%= archive.number %></td>
      <td><%= link_to archive.title, archive %></td>
      <td>
        <% archive.authors.each do |author| %>
          <%= link_to author.surname, author %><%= ', ' unless author == archive.authors.last %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>